# Modbus function codes
READ_COILS = 1
READ_DISCRETE_INPUTS = 2
READ_HOLDING_REGISTERS = 3
READ_INPUT_REGISTERS = 4
WRITE_SINGLE_COIL = 5
WRITE_SINGLE_REGISTER = 6
WRITE_MULTIPLE_COILS = 15
WRITE_MULTIPLE_REGISTERS = 16


# State code
IDLE = 0
MIXER = 1
SELECTOR = 2
PUMP_IN = 3
PUMP_OUT = 4
DONE = 5
